import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Form from '../components/Form'
import { Swiper, SwiperSlide } from 'swiper/react'
import { Pagination } from 'swiper/modules'

import 'swiper/css'
import 'swiper/css/pagination'

import hero1 from '/public/img/bg.jpg'
import hero2 from '/public/img/about-bg.jpg'
import ic_tw from '/public/img/twitter.png'
import ic_fb from '/public/img/facebook.png'
import ic_lightbulb from '/public/img/lightbulb.png'
import ic_balance from '/public/img/balance-scale.png'
import ic_bank from '/public/img/bank-icon.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <section className='mt-16 relative'>
        <Swiper
          pagination={{
            clickable: true,
          }}
          modules={[Pagination]}
          navigation
          className='mySwiper'
        >
          <SwiperSlide>
            <div className='h-[320px] lg:h-[500px]'>
              <div className='max-w-[1200px] mx-auto h-full relative px-4 lg:px-0 z-10'>
                <p className='absolute bottom-32 text-2xl lg:text-3xl font-semibold max-w-[720px] leading-relaxed text-white p-2 bg-black/80'>
                  THIS IS PLACE WHERE TECHNOLOGY & CREATIVITY FUSED INTO DIGITAL
                  CHEMISTRY
                </p>
              </div>
              <Image
                src={hero1}
                alt='hero 1'
                className='absolute w-full h-full object-cover top-0 left-0'
              />
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className='h-[320px] lg:h-[500px]'>
              <div className='max-w-[1200px] mx-auto h-full relative px-4 lg:px-0 z-10'>
                <p className='absolute bottom-32 text-2xl lg:text-3xl font-semibold max-w-[720px] leading-relaxed text-white p-2 bg-black/80'>
                  WE DONT HAVE THE BEST BUT WE HAVE THE GREATEST TEAM
                </p>
              </div>
              <Image
                src={hero2}
                alt='hero 1'
                className='absolute w-full h-full object-cover top-0 left-0'
              />
            </div>
          </SwiperSlide>
        </Swiper>
      </section>

      <section className='mt-16 lg:mt-20'>
        <div className='max-w-[1200px] mx-auto grid grid-cols-1 lg:grid-cols-3 gap-12 px-4 lg:px-0'>
          <div className='h-64 bg-red-400 flex justify-center px-10 relative'>
            <div className='text-center mt-8'>
              <Image
                src={ic_lightbulb}
                alt='icon'
                width={24}
                height={24}
                className='mx-auto'
              />
              <p className='text-white font-semibold mt-2'>INNOVATE</p>
              <p className='text-white text-sm mt-6'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
            </div>
            <div className='w-8 h-8 bg-red-500 absolute rotate-45 right-10 lg:-right-4 top-1/2 -translate-y-1/2 -z-10' />
          </div>
          <div className='h-64 bg-emerald-400 flex justify-center px-10 relative'>
            <div className='text-center mt-8'>
              <Image
                src={ic_bank}
                alt='icon'
                width={24}
                height={24}
                className='mx-auto'
              />
              <p className='text-white font-semibold mt-2'>LOYALTY</p>
              <p className='text-white text-sm mt-6'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
            </div>
            <div className='w-8 h-8 bg-emerald-500 absolute rotate-45 right-10 lg:-right-4 top-1/2 -translate-y-1/2 -z-10'/>

          </div>
          <div className='h-64 bg-sky-400 flex justify-center px-10 relative'>
            <div className='text-center mt-8'>
              <Image
                src={ic_balance}
                alt='icon'
                width={24}
                height={24}
                className='mx-auto'
              />
              <p className='text-white font-semibold mt-2'>RESPECT</p>
              <p className='text-white text-sm mt-6'>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className='mt-16 lg:mt-20'>
        <p className='text-center text-lg text-gray-800 font-semibold'>
          Contact Us
        </p>
        <Form />
      </section>

      <footer className='bg-gray-700 w-full py-3 mt-24'>
        <p className='text-center text-white'>Copyright 2016. PT Company</p>
        <div className='flex justify-center gap-4 items-center mt-4'>
          <Image src={ic_fb} alt='icon' className='w-4' />
          <Image src={ic_tw} alt='icon' className='w-4' />
        </div>
      </footer>
    </div>
  )
}
